### PR TITLE
Added Snake Game

### PR DESCRIPTION
**Pull request by gazal2708**

### CODE REVIEW

**Comment by Arindam200** [comment]
Thanks for Contributing again!
Keep Contributing.

**Comment by gazal2708** [comment]
Hi @Arindam200  can you please add hacktoberfest-approved label to this merged PR ??

**Comment by gazal2708** [comment]
Screenshot 2022-10-02 at 1 09 49 AM

**Comment by Arindam200** [comment]
Sorry for the late reply. I have labeled it.
Thanks.

**Pull request merged**
