### PR TITLE
Create Python Stone/Paper/Scissor Game

### PR DESCRIPTION
**Pull request by yashraj0114**
This is a stone paper game .

### CODE REVIEW

**Comment by yashraj0114** [comment]
@Arindam200 Bro see now I have add it in project folder.
Bro If I am doing it wrong please help me how to do because I am new to this.

**Review by Arindam200 — APPROVED** [review]

**Comment by Arindam200** [comment]
star this repo! 
Keep contributing!

**Comment by yashraj0114** [comment]
@Arindam200 thanks bro, I have given star.

**Comment by yashraj0114** [comment]
@Arindam200 Bro I am new to this, will you help me in tutorial . How to contribute to projects in github and merge and all.

**Comment by yashraj0114** [comment]
@Arindam200 bro it is showing excluded

**Pull request merged**
